In [118]:
import utm
from IPython.display import clear_output
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error
from sklearn import svm
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder

In [289]:
data = pd.read_csv(r'C:\Users\user\Desktop\Phd work\greenkof\Groenkloof Reserve Nature Sample Points 40 (0 - 20).csv')

In [290]:
data

Sample Point  Al (ppm)  SOC (g/kg)  TC (g/kg)  ECEC (mol (+)/kg  N (g/kg)  \
0           SP1      43.7        11.2       26.1               7.2       1.1   
1           SP2      43.7        11.2       26.1               8.0       1.0   
2           SP3      39.4        11.2       23.5               7.2       1.2   
3           SP4      39.4         9.0       19.1               7.2       1.0   
4           SP5      43.7         9.0       21.2               5.7       1.0   
5           SP6      43.7        10.0       21.2               6.4       1.1   
6           SP7      39.4         9.0       17.2               6.4       1.0   
7           SP8      39.4         8.0       15.4               5.7       1.0   
8           SP9      39.4         8.0       15.4               5.0       1.0   
9          SP10      35.6         8.0       15.4               5.0       1.0   
10         SP11      35.6         6.4       13.9               5.0       0.9   
11         SP12      35.6         9.0       17.2               5.7       0.9   
12         SP13      32.1         8.0       17.2               5.7       0.9   
13         SP14      35.6         9.0       17.2               6.4       0.9   
14         SP15      35.6         9.0       17.2               6.4       1.0   
15         SP16      35.6         9.0       15.4               6.4       1.0   
16         SP17      39.4        10.0       17.2               5.0       1.0   
17         SP18      43.7        10.0       15.4               6.4       1.0   
18         SP19      39.4         9.0       17.2               5.7       0.9   
19         SP20      43.7        11.2       23.5               6.4       1.1   
20         SP21      35.6         9.0       17.2               7.2       1.0   
21         SP22      39.4        11.2       21.2               6.4       1.2   
22         SP23      43.7         9.0       19.1               6.4       1.1   
23         SP24      39.4        10.0       17.2               6.4       1.0   
24         SP25      39.4        11.2       19.1               6.4       1.1   
25         SP26      39.4        11.2       23.5               7.2       1.2   
26         SP27      39.4        10.0       21.2               6.4       1.1   
27         SP28      43.7        11.2       21.2               8.0       1.1   
28         SP29      48.4        11.2       23.5               8.0       1.2   
29         SP30      48.4        11.2       23.5               8.0       1.1   
30         SP31      53.6        11.2       23.5               7.2       1.0   
31         SP32      43.7        10.0       21.2               6.4       1.1   
32         SP33      48.4        11.2       21.2               8.0       1.2   
33         SP34      53.6        11.2       23.5               8.0       1.1   
34         SP35      43.7        10.0       23.5               9.0       1.1   
35         SP36      48.4        11.2       21.2               6.4       1.1   
36         SP37      43.7        10.0       26.1               8.0       1.0   
37         SP38      32.1         8.0       15.4               6.4       1.0   
38         SP39      48.4         9.0       21.2               7.2       0.9   
39         SP40      43.7         9.0       19.1               7.2       1.1   

     PH  Ca (ppm)  Fe (ppm)  Mg (ppm)  P (ppm)  K (ppm)  S (ppm)  Zn (ppm)  \
0   5.9     402.4      89.0     163.0      8.0    108.9      4.5       1.7   
1   5.8     402.4      80.5     147.4      7.2    120.5      4.5       2.0   
2   5.9     402.4      89.0     147.4      6.4     98.5      5.7       2.0   
3   6.2     543.6      80.5     163.0      8.0    120.5      4.0       2.0   
4   5.9     491.7      80.5     147.4      7.2    120.5      4.0       1.5   
5   6.1     444.9      72.7     163.0      8.0    133.3      4.0       1.7   
6   6.0     364.0      80.5     147.4      9.0    133.3      4.0       1.5   
7   6.0     364.0      80.5     147.4      8.0    120.5      4.0       1.5   
8   6.0     444.9   

In [291]:
data.iloc[:4].values

array([['SP1', 43.7, 11.2, 26.1, 7.2, 1.1, 5.9, 402.4, 89.0, 163.0, 8.0,
        108.9, 4.5, 1.7, 5.3, -25.7752, 28.1961],
       ['SP2', 43.7, 11.2, 26.1, 8.0, 1.0, 5.8, 402.4, 80.5, 147.4, 7.2,
        120.5, 4.5, 2.0, 4.4, -25.7775, 28.1966],
       ['SP3', 39.4, 11.2, 23.5, 7.2, 1.2, 5.9, 402.4, 89.0, 147.4, 6.4,
        98.5, 5.7, 2.0, 4.4, -25.7815, 28.1939],
       ['SP4', 39.4, 9.0, 19.1, 7.2, 1.0, 6.2, 543.6, 80.5, 163.0, 8.0,
        120.5, 4.0, 2.0, 4.1, -25.7834, 28.201]], dtype=object)

In [311]:
X = []
Y = []

In [312]:
def trainerNN(pp_list):
    
    for i in range(len(pp_list)):
        lat = []
        
        lat.append(pp_list[i][-2])
        lat.append(pp_list[i][-1])
        X.append(lat)
        Y.append(pp_list[i][2])

In [313]:
trainerNN(data.iloc[:].values)

In [314]:
X = np.array(X, dtype=float)
Y = np.array(Y, dtype=float)
X, Y

(array([[-25.7752,  28.1961],
        [-25.7775,  28.1966],
        [-25.7815,  28.1939],
        [-25.7834,  28.201 ],
        [-25.7993,  28.2221],
        [-25.8008,  28.2195],
        [-25.8022,  28.2164],
        [-25.8039,  28.2126],
        [-25.8053,  28.2097],
        [-25.8051,  28.211 ],
        [-25.8068,  28.2085],
        [-25.8084,  28.2051],
        [-25.8095,  28.203 ],
        [-25.8065,  28.2033],
        [-25.8042,  28.1997],
        [-25.8042,  28.2047],
        [-25.8017,  28.2092],
        [-25.7993,  28.2133],
        [-25.7974,  28.2167],
        [-25.7968,  28.2198],
        [-25.7953,  28.2153],
        [-25.7966,  28.2123],
        [-25.7975,  28.2088],
        [-25.7992,  28.205 ],
        [-25.8   ,  28.2015],
        [-25.8003,  28.1979],
        [-25.7977,  28.1992],
        [-25.7937,  28.1979],
        [-25.7911,  28.2021],
        [-25.7895,  28.205 ],
        [-25.7882,  28.2083],
        [-25.7919,  28.204 ],
        [-25.79  ,  28.1999],
        [-

In [315]:
X_train, X_test, Y_train, Y_test = np.array(X[0:int(round(len(X))*0.80)]), X[int(round(len(X))*0.80):], Y[:int(round(len(X))*0.80)], Y[int(round(len(X))*0.80):]

In [316]:
X_train.shape

(32, 2)

In [317]:
Y_train.shape

(32,)

In [318]:
lr = KNeighborsRegressor(n_neighbors=4)

In [319]:
lr.fit(X_train, Y_train)

KNeighborsRegressor(n_neighbors=4)

In [320]:
Y_pred = lr.predict(X_test)

In [321]:
mean_squared_error(Y_test, Y_pred, squared=False)

0.7937253933193766

In [322]:
Y_pred

array([10.9 , 10.9 , 10.65, 10.9 , 10.65,  8.75, 10.65,  9.8 ])

In [323]:
Y_test

array([11.2, 11.2, 10. , 11.2, 10. ,  8. ,  9. ,  9. ])